config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :is_logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def is_logged_in?
    !!current_user
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @messages = Message.all
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel', content: render_message(message)
    end
  end

  private
    def message_params
      params.require(:message).permit(:body)
    end

    def render_message message
      render partial: 'message', locals: {message: message}
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "ログインしました。"
      redirect_to root_path
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_path
  end

  private
    def logged_in_redirect
      if is_logged_in?
        flash[:notice] = "すでにログインしています。"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class="flex justify-center h-full">
  <div class="flex flex-col flex-initial box-border h-full w-full p-4 border border-gray-400">
    <div class="h-full overflow-scroll mb-2 js-message-container">
      <%= render @messages %>
    </div>
    <%= form_for(@message, url: message_path, html: {class: "flex mt-auto"}, remote: true) do |f| %>
      <%= f.text_field :body, {placeholder: "メッセージを入力", class: "flex-initial h-4 p-4 mr-2 text-sm w-11/12 border rounded"} %>
      <%= f.button "送信", {class: "flex-initial btn bg-blue-500 hover:bg-blue-700 text-white text-sm font-bold py-1 px-2 rounded w-1/12"} %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="text-center <%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-500 p-6">
  <div class="w-full block flex-grow flex items-center px-20">
    <div class="text-sm flex-grow">
      <%= link_to "Home", root_path, class: "block inline-block mt-0 text-blue-200 hover:text-white mr-4" %>
    </div>
    <div class="dropdown">
      <div class="text-white px-2 py-1 rounded inline-flex items-center mr-1">
      <span class="mr-1">Account</span>
      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/> </svg>
      </div>
      <ul class="dropdown-menu absolute hidden text-gray-700 pt-1">
        <% if is_logged_in? %>
          <li class="">
            <%= button_to "Logout", logout_path, method: "delete", class: "bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" %>
          </li>
        <% else %>
          <li class="">
            <%= link_to "Login", login_path, class: "bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" %>
          </li>
          <li class="">
            <a class="bg-gray-200 hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap rounded-b" href="#">SignUp</a>
          </li>
        <% end %>
      </ul>
    </div>

    <% unless is_logged_in? %>
      <div>
        <a href="#" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-0">Sign Up</a>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css", media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <div class="container mx-auto px-6 py-6">
      <%= yield %>
    </div>
    <%= debug params if Rails.env.development? %>
  </body>
</html>

app/views/messages/_message.html.erb
<p><%= message.user.name %>: <%= message.body %></p>